name: Rust

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set tag to rust/Cargo.toml
        run: |
          tag=$(echo $GITHUB_REF | cut -d"/" -f3)
          echo "tag value: $tag"
          sed -i "s!__tag_ref__!$tag!g" rust/Cargo.toml
      - name: Build
        run: cargo build --verbose --manifest-path rust/Cargo.toml
      - name: Run tests
        run: cargo test --verbose --manifest-path rust/Cargo.toml
      - name: Publish
        run: cargo publish --verbose --manifest-path rust/Cargo.toml --dry-run
