name: Rust

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --manifest-path rust/Cargo.toml
      - name: Run tests
        run: cargo test --verbose --manifest-path rust/Cargo.toml
    #- name: Publish
    #  run: cargo publish --verbose --manifest-path rust/Cargo.toml
